dist: xenial
language: ruby
bundler_args: --without development
rvm:
  - 2.4.9
services:
  - postgresql
before_script:
  - bundle exec rake db:create db:schema:load

script:
  - bundle exec rake
addons:
  code_climate:
    repo_token: 9b6a47d42b4a745a38818eac18dba4ca94ea88f8c7751859ec49b8cedbf010fe
  chrome: stable
notifications:
  email:
    - social@codebar.io
